### ISSUE TITLE
Timestamp from the moment when pg_gather is executed

### ISSUE THREAD

**Issue by laudares** [jobinau/pg_gather#13]
It would be very good to have the time when pg_gather started to collect data logged and displayed in the header of the HTML report. Something as simple as:
`select now(); show log_timezone;`
we could later use to match entries in the PostgreSQL log and/or other monitoring systems.

**Comment by jobinau** [comment]
Thank @laudares  for reporting this.
The logic is already existing. But unfortunately fails for Amazon Aurora
So considering his as a bug report.

**Comment by jobinau** [comment]
Committed modification for Aurora handling. commit 
https://github.com/jobinau/pg_gather/commit/ff4996cdbea44f6cf8b9088136d02aa2b1f1a457 and 
https://github.com/jobinau/pg_gather/commit/b4c7884a636d3e933b87a4322d1d1df321dd12fa

For Aurora, Just need to run a `sed` command after downloading the `gather.sql`.
Overall steps looks like
```
curl -LO https://raw.githubusercontent.com/jobinau/pg_gather/main/gather.sql
sed -i 's/^CASE WHEN pg_is_in_recovery().*/NULL/' gather.sql
```

**Comment by jobinau** [comment]
Committed modification for Aurora handling. commit https://github.com/jobinau/pg_gather/commit/ff4996cdbea44f6cf8b9088136d02aa2b1f1a457 and https://github.com/jobinau/pg_gather/commit/b4c7884a636d3e933b87a4322d1d1df321dd12fa

For Aurora, Just need to run a `sed` command after downloading the `gather.sql`.
Overall steps look like
```
curl -LO https://raw.githubusercontent.com/jobinau/pg_gather/main/gather.sql
sed -i 's/^CASE WHEN pg_is_in_recovery().*/NULL/' gather.sql
```
