### ISSUE TITLE
New feature: Adding OID information to displayed objects

### ISSUE THREAD

**Issue by psvampa** [jobinau/pg_gather#47]
Hello Jobin,
Over the last time, I got a few scenarios where I needed to deal with OIDs. During those cases, I found myself spending some time looking for the OIDs of different objects to achieve my own goals.
I wonder whether providing visibility on the OIDs would be useful, at least for those tables and indexes we are already displaying in the pg_gather report.
Best Regards,

**Comment by jobinau** [comment]
Thank you @psvampa for this feature request. 
Since we already capture OID in pg_gather its a matter of placing it in the report.

**Comment by jobinau** [comment]
Table OID is now part of the pop window on mouseover on the table name.
part of commit: https://github.com/jobinau/pg_gather/commit/d035733f64d5a0dd2daddb951f58707367f1c908
Testing so far is good.  Planning to include this in Release 27
