### ISSUE TITLE
Provide a list of extensions

### ISSUE THREAD

**Issue by arronax** [jobinau/pg_gather#7]
A feature request: provide a list of extensions that are installed and that are available.
Right now, the only way to guess what's installed/available is by looking at the value of shared_preload_libraries.

**Comment by jobinau** [comment]
Feature request accepted. 
Work-in-Progress.

**Comment by jobinau** [comment]
The new feature is implemented by the commit : 
https://github.com/jobinau/pg_gather/commit/95d4ada9edac31c43ecbbd65426e3a639714c645
